version: "3.0"
services:
  foodcare-api:
    container_name: foodcare-api
    build: ./
    volumes:
      - ./:/app/foodcare-api
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
